--[[
xtreader — one account across every reader you own.

Four sync paths, three of which need no server change at all:

  * reading progress — KOReader's own kosync plugin, pointed at this server and
    configured with the credential provisioned at pairing. Wire-compatible by
    design, so nothing here reimplements it.
  * books           — GET /library/manifest, reconciled against disk
  * wallpapers      — GET /wallpapers/manifest, into the screensaver folder
  * telemetry       — POST /devices/heartbeat

Everything network-facing goes through NetworkMgr:runWhenOnline. One Kindle
caveat worth knowing: when liblipclua is missing, KOReader's Kindle backend
turns the radio on and calls the completion callback immediately rather than
waiting for an address, so the first request after a cold radio can fail. That
is not an error worth a dialog — it is a retry.
]]

local ConfirmBox = require("ui/widget/confirmbox")
local Dispatcher = require("dispatcher")
local InfoMessage = require("ui/widget/infomessage")
local InputDialog = require("ui/widget/inputdialog")
local NetworkMgr = require("ui/network/manager")
local UIManager = require("ui/uimanager")
local WidgetContainer = require("ui/widget/container/widgetcontainer")
local logger = require("logger")
local _ = require("gettext")
local T = require("ffi/util").template

local Api = require("api")
local Heartbeat = require("heartbeat")
local Insights = require("insights")
local KindleHistory = require("kindle_history")
local Library = require("library")
local Pairing = require("pairing")
local Store = require("store")
local Wallpaper = require("wallpaper")

local Xtreader = WidgetContainer:extend({
    name = "xtreader",
    is_doc_only = false,
})

function Xtreader:onDispatcherRegisterActions()
    Dispatcher:registerAction("xtreader_sync", {
        category = "none",
        event = "XtreaderSync",
        title = _("xtreader: sync now"),
        general = true,
    })
end

function Xtreader:init()
    self.store = Store:open()
    self.api = Api.new(self.store)
    self:onDispatcherRegisterActions()
    self.ui.menu:registerToMainMenu(self)
end

--------------------------------------------------------------------------------
-- Automatic, quiet sync
--------------------------------------------------------------------------------

-- Reading statistics accumulate every day and only ever left this device when
-- somebody remembered to press a button. That is the wrong shape for data that
-- is generated passively: the dashboard was months behind and nothing on either
-- end said so.
--
-- WHY RESUME AND NOT SUSPEND
--
-- Waking is the moment the radio comes back and the reader is not looking at
-- anything yet. Suspending is the opposite: the device is on its way down, and a
-- request issued there is one that gets frozen mid-flight and resumed against a
-- socket the other end closed long ago. The data is the same either way -- it is
-- still sitting in statistics.sqlite3 -- so there is nothing to gain by racing
-- the power state.
--
-- WHAT IT WILL NOT DO
--
-- It will not turn the radio on. `runWhenOnline` would, and that is how a quiet
-- background task becomes "Connecting to Wi-Fi…" over the page the reader is
-- on -- the exact thing the quiet-sync patch in this repo exists to remove.
-- `isConnected` is `ifHasAnAddress` on Kindle (kindle/device.lua:524): does this
-- interface have an address right now, no DNS, no blocking.
--
-- It also will not sync books or wallpapers. Those move megabytes and change
-- what is on disk; they stay a decision the reader makes. This carries the rows
-- that were generated by reading and nothing else.
local AUTO_MIN_GAP = 30 * 60

function Xtreader:autoSyncEnabled()
    return G_reader_settings:nilOrTrue("xtreader_auto_sync")
end

function Xtreader:maybeAutoSync(why)
    if not (self.store and self.store:isPaired()) then return end
    if not self:autoSyncEnabled() then return end
    if not NetworkMgr:isConnected() then return end

    local now = os.time()
    local last = tonumber(self.store:get("auto_sync_at")) or 0
    if now - last < AUTO_MIN_GAP then return end

    -- Stamped BEFORE the attempt, not after. A run that fails must not leave the
    -- gap open, or every network event for the rest of the session retries it --
    -- and the rows are not lost by waiting, because the watermark only advances
    -- on a batch the server confirmed.
    self.store:set("auto_sync_at", now)
    self.store:flush()

    logger.dbg("xtreader: quiet sync on", why)
    local ok, err = pcall(function()
        -- report() that draws nothing: Insights expects a progress callback and
        -- treats false as "the user asked to stop".
        local silent = function() return true end
        local sent = Insights.sync(self.api, self.store, silent)
        Heartbeat.send(self.api, self.store, sent and "ok" or "failed")
    end)
    if not ok then
        logger.warn("xtreader: quiet sync failed, will retry after the gap:", tostring(err))
    end
end

-- Both handlers return nothing on purpose. These events are broadcast, and a
-- handler that returned true would consume them -- stopping every widget below
-- us from ever hearing that the device woke or that the network came up.

function Xtreader:onResume()
    -- Wi-Fi is rarely up at the instant of resume; auto_restore_wifi brings it
    -- back a moment later. Ask again once it has had time rather than reading a
    -- radio that is still starting.
    UIManager:scheduleIn(20, function() self:maybeAutoSync("resume") end)
end

function Xtreader:onNetworkConnected()
    UIManager:scheduleIn(3, function() self:maybeAutoSync("network") end)
end

function Xtreader:onFlushSettings()
    if self.store and self.store.dirty then
        self.store:flush()
    end
end

local function notify(text, timeout)
    UIManager:show(InfoMessage:new({ text = text, timeout = timeout or 5 }))
end

--- Sends one heartbeat and returns the wallpaper fingerprint it came back with.
--
-- Called after every path that reaches the server, not just a full sync. The
-- dashboard's battery and card figures come from nowhere else, so a device that
-- only ever ran a partial sync would sit there reporting "Unknown" forever with
-- nothing on screen explaining why.
--
-- Returns the fingerprint and deliberately does NOT store it.
-- `wallpaper_revision` means "the set we last successfully synced against", not
-- "the last number the server said". Recording it here would mark the device up
-- to date before a single image had been downloaded, and the equality check
-- would then suppress every future wallpaper sync. Only wallpaper sync writes
-- that key, and only once it has actually run.
function Xtreader:beat(status)
    return Heartbeat.send(self.api, self.store, status)
end

--- Runs `fn(report)` inside a Trapper coroutine so the UI stays responsive and
--- the user can stop a long run by tapping the progress message.
-- `opts.beat` sends a heartbeat once `fn` is done; syncAll does its own, mid-run.
function Xtreader:runSync(fn, opts)
    opts = opts or {}
    NetworkMgr:runWhenOnline(function()
        local Trapper = require("ui/trapper")
        Trapper:wrap(function()
            Trapper:setPausedText(_("Sync paused. Continue or abort?"))
            local report = function(text)
                return Trapper:info(text)
            end
            local ok, message = fn(report)
            if opts.beat then
                self:beat(ok and "ok" or "failed")
            end
            Trapper:clear()
            notify(message or (ok and _("Done.") or _("Failed.")), ok and 5 or 10)
        end)
    end)
end

function Xtreader:syncAll(report)
    local lines = {}
    local ok_books, books_msg = Library.sync(self.api, self.store, report)
    lines[#lines + 1] = books_msg

    -- Reported AFTER the book sync, never before: the point of the snapshot is
    -- what is on the card now, and running it first would describe the device as
    -- it was a moment ago -- wrong by exactly the files this sync just added or
    -- removed.
    --
    -- Its failure is not the caller's business. The server uses this to warn the
    -- owner before deleting the last copy of something; a report that did not
    -- land means one stale warning, not a book in the wrong place, and the next
    -- sync replaces it wholesale anyway.
    local inv_ok, inv = Library.reportInventory(self.api, self.store)
    if not inv_ok then
        logger.dbg("xtreader: inventory report failed:", tostring(inv))
    end

    -- Reading statistics ride the same button.
    --
    -- They used to be reachable only from their own menu entry, which meant a
    -- device that synced every day still reported no reading at all until
    -- someone remembered that one item existed. "Sync" that leaves out the one
    -- thing accumulating every day is not sync.
    --
    -- Its result deliberately does NOT decide the overall one. A statistics
    -- upload that fails costs nothing permanent -- the watermark only moves on a
    -- confirmed batch, so the rows are still there next time -- while books
    -- landing on disk is what the caller actually needs to hear about.
    local _ok_stats, stats_msg = Insights.sync(self.api, self.store, report)
    lines[#lines + 1] = stats_msg

    -- The heartbeat rides a request we owe the server anyway, and its reply
    -- says whether the wallpaper set moved. Comparing the fingerprint saves a
    -- manifest round trip on the common no-change run.
    local revision = Heartbeat.send(self.api, self.store, ok_books and "ok" or "failed")
    if Heartbeat.wallpapersChanged(self.store, revision) then
        local ok_wp, wp_msg = Wallpaper.sync(self.api, self.store, report)
        lines[#lines + 1] = wp_msg
        -- Only a sync that actually succeeded may claim this fingerprint. A
        -- failed run that recorded it would leave the device permanently
        -- convinced it was up to date and stop trying.
        if ok_wp and revision then
            self.store:set("wallpaper_revision", revision)
        end
    else
        lines[#lines + 1] = _("Wallpapers already up to date.")
    end

    self.store:flush()
    return ok_books, table.concat(lines, "\n")
end

function Xtreader:pair()
    NetworkMgr:runWhenOnline(function()
        Pairing.start(self.api, self.store, self.ui, function(ok, message)
            if ok then
                -- Pairing is the first moment a device row exists, and the
                -- dashboard has nothing to show for it until a heartbeat
                -- arrives. Sending one here means the reader appears complete
                -- the moment it is approved, rather than after some later sync
                -- the owner has no reason to know they need to run.
                self:beat("never")
            end
            notify(message, ok and 8 or 10)
        end)
    end)
end

function Xtreader:unpair()
    UIManager:show(ConfirmBox:new({
        text = _("Forget this server?\n\nBooks already downloaded stay on the device. Progress sync stops."),
        ok_text = _("Forget"),
        ok_callback = function()
            self.store:clearCredentials()
            notify(_("Unpaired."))
        end,
    }))
end

function Xtreader:editSetting(key, title)
    local dialog
    dialog = InputDialog:new({
        title = title,
        input = tostring(self.store:get(key) or ""),
        buttons = { {
            { text = _("Cancel"), id = "close", callback = function() UIManager:close(dialog) end },
            {
                text = _("Save"),
                is_enter_default = true,
                callback = function()
                    local value = dialog:getInputText()
                    if value and value ~= "" then
                        self.store:set(key, (value:gsub("%s+$", "")))
                        self.store:flush()
                    end
                    UIManager:close(dialog)
                end,
            },
        } },
    })
    UIManager:show(dialog)
    dialog:onShowKeyboard()
end

function Xtreader:statusText()
    if not self.store:isPaired() then
        return _("Not paired.")
    end
    local last = self.store:get("last_library_sync")
    return T(_("Paired as %1.\nServer: %2\nBooks: %3\nLast sync: %4"),
             self.store:get("device_name") or "?",
             self.store:get("base_url"),
             self.store:get("library_dir"),
             last and last > 0 and os.date("%Y-%m-%d %H:%M", last) or _("never"))
end

function Xtreader:addToMainMenu(menu_items)
    menu_items.xtreader = {
        text = _("xtreader"),
        sorting_hint = "tools",
        sub_item_table = {
            {
                text = _("Sync now"),
                enabled_func = function() return self.store:isPaired() end,
                callback = function()
                    self:runSync(function(report) return self:syncAll(report) end)
                end,
            },
            {
                text = _("Sync books only"),
                enabled_func = function() return self.store:isPaired() end,
                callback = function()
                    self:runSync(function(report)
                        return Library.sync(self.api, self.store, report)
                    end, { beat = true })
                end,
            },
            {
                text = _("Upload this device's books"),
                enabled_func = function() return self.store:isPaired() end,
                help_text = _("Sends every book in your books folder that the account does not already have, so books that exist only on this device become account books and survive it.\n\nOnly one reader per account may upload, chosen in the device list on the web. Until one is chosen this is refused, and it is refused before anything is sent.\n\nBooks already on the account are skipped without being sent again."),
                callback = function()
                    local Upload = require("upload")
                    local function go()
                        self:runSync(function(report)
                            return Upload.pushAll(self.api, self.store, report)
                        end, { beat = true })
                    end
                    -- Ask once when nothing is excluded.
                    --
                    -- Not paternalism: a books folder that came from a Kindle
                    -- normally contains the ORIGINALS beside the converted
                    -- copies, so an unfiltered first push sends every one of
                    -- those books twice, under two paths, and the account has
                    -- no way to know. That happened on the device this was
                    -- written on -- the upload was already running before it
                    -- was noticed, and the only way to stop it was a signal
                    -- over SSH.
                    --
                    -- Only when the list is EMPTY: somebody who has set one has
                    -- thought about this and does not need asking again.
                    local skip = self.store:get("upload_skip")
                    if skip and skip ~= "" then return go() end

                    local root = self.store:get("library_dir")
                    local books = root and Upload.scan(root) or {}
                    local mb = 0
                    for _i, b in ipairs(books) do mb = mb + (b.size or 0) end
                    mb = math.floor(mb / 1048576)

                    UIManager:show(ConfirmBox:new{
                        text = T(_("Upload all %1 books (%2 MB)?\n\nNothing is excluded. If this folder holds the original files a converted copy was made from, both go up as separate books.\n\nSet \"Folders to leave out of uploads\" first if that applies."),
                                 #books, mb),
                        ok_text = _("Upload all"),
                        ok_callback = go,
                        cancel_text = _("Not yet"),
                    })
                end,
            },
            {
                text = _("Check what would be uploaded"),
                enabled_func = function() return self.store:isPaired() end,
                help_text = _("Counts and measures without sending anything: how many books the account does not have, how many it already has, and how many sit at a path the account gives to a different book.\n\nRun this first. It cannot tell you whether this reader is allowed to upload -- the server only answers that when something is actually sent."),
                callback = function()
                    local Upload = require("upload")
                    self:runSync(function(report)
                        return Upload.dryRun(self.api, self.store, report)
                    end)
                end,
            },
            {
                text = _("Send reading statistics"),
                enabled_func = function() return self.store:isPaired() end,
                help_text = _("Uploads KOReader's own per-page reading records so the web dashboard can show streaks, heatmaps and reading time across every reader on the account. Reads the statistics database, never writes to it."),
                callback = function()
                    self:runSync(function(report)
                        return Insights.sync(self.api, self.store, report)
                    end, { beat = true })
                end,
            },
            {
                text = _("Sync wallpapers only"),
                enabled_func = function() return self.store:isPaired() end,
                separator = true,
                callback = function()
                    self:runSync(function(report)
                        return Wallpaper.sync(self.api, self.store, report)
                    end, { beat = true })
                end,
            },
            {
                text = _("Pair this device"),
                enabled_func = function() return not self.store:isPaired() end,
                callback = function() self:pair() end,
            },
            {
                text = _("Unpair"),
                enabled_func = function() return self.store:isPaired() end,
                callback = function() self:unpair() end,
            },
            {
                text = _("Reapply progress sync settings"),
                enabled_func = function() return self.store:isPaired() end,
                separator = true,
                help_text = _("Points KOReader's progress sync at this server and sets binary (content) matching, which is what the CrossPoint reader uses and what stock KOReader defaults to. A mismatch here makes sync appear to do nothing at all."),
                callback = function()
                    local ok, err, hint = Pairing.configureKosync(self.store, self.ui)
                    if not ok then
                        notify(T(_("Failed: %1"), tostring(err)))
                    elseif hint == "applies_on_next_book" then
                        notify(_("Progress sync reconfigured.\nIt takes effect when you next open a book — KOReader only loads the sync plugin while a document is open."))
                    else
                        notify(_("Progress sync reconfigured."))
                    end
                end,
            },
            {
                text = _("Server address"),
                callback = function() self:editSetting("base_url", _("Server address")) end,
            },
            {
                text = _("Books folder"),
                callback = function() self:editSetting("library_dir", _("Books folder")) end,
            },
            {
                text = _("Folders to leave out of uploads"),
                help_text = _("Comma-separated names of top-level folders inside your books folder that \"Upload this device's books\" should skip.\n\nWorth setting before the first upload: a folder of original Kindle files that were converted to EPUB and filed elsewhere would otherwise put every one of those books on the account twice, and DRM-protected purchases would upload bytes that cannot be opened anywhere else.\n\nOnly matches at the top level. Leave empty to upload everything."),
                callback = function()
                    local dialog
                    dialog = InputDialog:new({
                        title = _("Folders to leave out of uploads"),
                        input = tostring(self.store:get("upload_skip") or ""),
                        input_hint = _("Downloads, dictionaries"),
                        buttons = { {
                            { text = _("Cancel"), id = "close",
                              callback = function() UIManager:close(dialog) end },
                            {
                                text = _("Save"),
                                is_enter_default = true,
                                callback = function()
                                    -- Saved even when empty, unlike editSetting:
                                    -- clearing the list is a thing a reader will
                                    -- want to do, and a Save that silently keeps
                                    -- the old value is worse than no button.
                                    local value = dialog:getInputText() or ""
                                    self.store:set("upload_skip", (value:gsub("^%s+", ""):gsub("%s+$", "")))
                                    self.store:flush()
                                    UIManager:close(dialog)
                                end,
                            },
                        } },
                    })
                    UIManager:show(dialog)
                    dialog:onShowKeyboard()
                end,
            },
            {
                text = _("Wallpapers folder"),
                separator = true,
                callback = function()
                    self:editSetting("wallpaper_dir", _("Wallpapers folder"))
                    Wallpaper.configureScreensaver(self.store)
                end,
            },
            {
                text = _("Download every book automatically"),
                checked_func = function()
                    return G_reader_settings:isTrue("xtreader_auto_download")
                end,
                help_text = _("Off: a book on your account that is not on this device is shown in its folder as a placeholder, greyed out, and is fetched when you tap it. Deleting a book here then means what it says -- it stays gone until you ask for it again.\n\nOn: every sync pulls down anything missing, so the device always mirrors the account. Deleting a book locally is undone by the next sync."),
                callback = function()
                    G_reader_settings:flipNilOrFalse("xtreader_auto_download")
                end,
            },
            {
                text = _("Sync in the background"),
                checked_func = function() return self:autoSyncEnabled() end,
                help_text = _("When the device wakes and Wi-Fi is already up, send reading statistics without showing anything. Nothing is drawn on success or on failure, and the radio is never switched on for it -- if Wi-Fi is off, the rows simply wait for a wake when it is on.\n\nBooks and wallpapers are not included; those stay manual."),
                separator = true,
                callback = function()
                    G_reader_settings:saveSetting("xtreader_auto_sync", not self:autoSyncEnabled())
                end,
            },
            {
                text = _("Status"),
                keep_menu_open = true,
                callback = function() notify(self:statusText(), 10) end,
            },
        },
    }

    self:addKindleImport(menu_items)
end

--- Adds the Kindle import, but only where there is a Kindle library to import.
--
-- Inserted after the fact rather than written into the table above, and omitted
-- entirely rather than greyed out: on a Kobo there is no `/var/local/cc.db` and
-- never will be, so a permanently disabled row would be asking the reader to
-- wonder what they did wrong.
--
-- NOTE: the endpoint this posts to is not live yet. Until it is, the item runs
-- and reports the server's error, which is the honest failure -- it reads the
-- catalogue correctly either way.
function Xtreader:addKindleImport(menu_items)
    if not KindleHistory.available() then
        return
    end
    table.insert(menu_items.xtreader.sub_item_table, 4, {
        text = _("Import Kindle reading history"),
        enabled_func = function() return self.store:isPaired() end,
        separator = true,
        help_text = _("Reads the library the Kindle's own software keeps -- which books are on the device and how far through each one you got -- and lists it on the dashboard.\n\nIt is kept apart from your reading statistics on purpose. The Kindle records no times, so this can say what you read but never when, and mixing it in would invent hours you never sat through."),
        callback = function()
            self:runSync(function(report)
                return KindleHistory.sync(self.api, self.store, report)
            end, { beat = true })
        end,
    })
end

function Xtreader:onXtreaderSync()
    if not self.store:isPaired() then
        notify(_("Pair this device with xtreader first."))
        return true
    end
    self:runSync(function(report) return self:syncAll(report) end)
    return true
end

return Xtreader
